import { Inter } from "next/font/google";
import "./globals.css";
import { MichiProvider } from "./context/MichiContext";
import { MichiCreateAndEditedProvider } from "./context/MichiCreateAndEditedContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MichiProvider>
    <MichiCreateAndEditedProvider>
   

   
    <html lang="en">
      <body className={inter.className}>{children}</body>

    </html>
   
    </MichiCreateAndEditedProvider>
    </MichiProvider>
  );
}
