import "./globals.css";
import localFont from "next/font/local";
import { MichiProvider } from "./context/MichiContext";
import { MichiCreateAndEditedProvider } from "./context/MichiCreateAndEditedContext";
const SpaceMonkey = localFont({
  src: [
    {
      path: "../../public/font/SpaceMonkeyBold-Ea5On.otf",
      weight: "400",
    },
  ],
});
import { Metadata } from "next";

export const metadata = {
  title: "Pet Maker",
  description: "Generated by create next app",

  icons: {
    icon: "/star.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <MichiProvider>
      <MichiCreateAndEditedProvider>
        <html lang="en">
          <body className={SpaceMonkey.className}>{children}</body>
        </html>
      </MichiCreateAndEditedProvider>
    </MichiProvider>
  );
}
